language: go
go:
    - tip
notifications:
    irc:
        channels:
            - "irc.mozilla.org#heka"
before_install:
    - sudo apt-get install protobuf-compiler cmake

install:
    - . build.sh

script:
    - make test
