[Timezones]
AD = "Europe/Andorra"
AE = "Asia/Dubai"
AF = "Asia/Kabul"
AG = "America/Antigua"
AI = "America/Anguilla"
AL = "Europe/Tirane"
AM = "Asia/Yerevan"
AN = "America/Curacao"
AO = "Africa/Luanda"
AQ = "Antarctica/South_Pole"
AR01 = "America/Argentina/Buenos_Aires"
AR02 = "America/Argentina/Catamarca"
AR03 = "America/Argentina/Tucuman"
AR04 = "America/Argentina/Rio_Gallegos"
AR05 = "America/Argentina/Cordoba"
AR06 = "America/Argentina/Tucuman"
AR07 = "America/Argentina/Buenos_Aires"
AR08 = "America/Argentina/Buenos_Aires"
AR09 = "America/Argentina/Tucuman"
AR10 = "America/Argentina/Jujuy"
AR11 = "America/Argentina/San_Luis"
AR12 = "America/Argentina/La_Rioja"
AR13 = "America/Argentina/Mendoza"
AR14 = "America/Argentina/Buenos_Aires"
AR15 = "America/Argentina/San_Luis"
AR16 = "America/Argentina/Buenos_Aires"
AR17 = "America/Argentina/Salta"
AR18 = "America/Argentina/San_Juan"
AR19 = "America/Argentina/San_Luis"
AR20 = "America/Argentina/Rio_Gallegos"
AR21 = "America/Argentina/Buenos_Aires"
AR22 = "America/Argentina/Catamarca"
AR23 = "America/Argentina/Ushuaia"
AR24 = "America/Argentina/Tucuman"
AS = "Pacific/Pago_Pago"
AT = "Europe/Vienna"
AU01 = "Australia/Sydney"
AU02 = "Australia/Sydney"
AU03 = "Australia/Darwin"
AU04 = "Australia/Brisbane"
AU05 = "Australia/Adelaide"
AU06 = "Australia/Hobart"
AU07 = "Australia/Melbourne"
AU08 = "Australia/Perth"
AW = "America/Aruba"
AX = "Europe/Mariehamn"
AZ = "Asia/Baku"
BA = "Europe/Sarajevo"
BB = "America/Barbados"
BD = "Asia/Dhaka"
BE = "Europe/Brussels"
BF = "Africa/Ouagadougou"
BG = "Europe/Sofia"
BH = "Asia/Bahrain"
BI = "Africa/Bujumbura"
BJ = "Africa/Porto-Novo"
BL = "America/St_Barthelemy"
BM = "Atlantic/Bermuda"
BN = "Asia/Brunei"
BO = "America/La_Paz"
BQ = "America/Curacao"
BR01 = "America/Rio_Branco"
BR02 = "America/Maceio"
BR03 = "America/Sao_Paulo"
BR04 = "America/Manaus"
BR05 = "America/Bahia"
BR06 = "America/Fortaleza"
BR07 = "America/Sao_Paulo"
BR08 = "America/Sao_Paulo"
BR11 = "America/Campo_Grande"
BR13 = "America/Belem"
BR14 = "America/Cuiaba"
BR15 = "America/Sao_Paulo"
BR16 = "America/Belem"
BR17 = "America/Recife"
BR18 = "America/Sao_Paulo"
BR20 = "America/Fortaleza"
BR21 = "America/Sao_Paulo"
BR22 = "America/Recife"
BR23 = "America/Sao_Paulo"
BR24 = "America/Porto_Velho"
BR25 = "America/Boa_Vista"
BR26 = "America/Sao_Paulo"
BR27 = "America/Sao_Paulo"
BR28 = "America/Maceio"
BR29 = "America/Sao_Paulo"
BR30 = "America/Recife"
BR31 = "America/Araguaina"
BS = "America/Nassau"
BT = "Asia/Thimphu"
BV = "Antarctica/Syowa"
BW = "Africa/Gaborone"
BY = "Europe/Minsk"
BZ = "America/Belize"
CAAB = "America/Edmonton"
CABC = "America/Vancouver"
CAMB = "America/Winnipeg"
CANB = "America/Halifax"
CANL = "America/St_Johns"
CANS = "America/Halifax"
CANT = "America/Yellowknife"
CANU = "America/Rankin_Inlet"
CAON = "America/Toronto"
CAPE = "America/Halifax"
CAQC = "America/Montreal"
CASK = "America/Regina"
CAYT = "America/Whitehorse"
CC = "Indian/Cocos"
CD01 = "Africa/Kinshasa"
CD02 = "Africa/Kinshasa"
CD03 = "Africa/Kinshasa"
CD04 = "Africa/Lubumbashi"
CD05 = "Africa/Lubumbashi"
CD06 = "Africa/Kinshasa"
CD07 = "Africa/Lubumbashi"
CD08 = "Africa/Kinshasa"
CD09 = "Africa/Lubumbashi"
CD10 = "Africa/Lubumbashi"
CD11 = "Africa/Lubumbashi"
CD12 = "Africa/Lubumbashi"
CF = "Africa/Bangui"
CG = "Africa/Brazzaville"
CH = "Europe/Zurich"
CI = "Africa/Abidjan"
CK = "Pacific/Rarotonga"
CL = "America/Santiago"
CM = "Africa/Lagos"
CN01 = "Asia/Shanghai"
CN02 = "Asia/Shanghai"
CN03 = "Asia/Shanghai"
CN04 = "Asia/Shanghai"
CN05 = "Asia/Harbin"
CN06 = "Asia/Chongqing"
CN07 = "Asia/Shanghai"
CN08 = "Asia/Harbin"
CN09 = "Asia/Shanghai"
CN10 = "Asia/Shanghai"
CN11 = "Asia/Chongqing"
CN12 = "Asia/Shanghai"
CN13 = "Asia/Urumqi"
CN14 = "Asia/Chongqing"
CN15 = "Asia/Chongqing"
CN16 = "Asia/Chongqing"
CN18 = "Asia/Chongqing"
CN19 = "Asia/Harbin"
CN20 = "Asia/Harbin"
CN21 = "Asia/Chongqing"
CN22 = "Asia/Harbin"
CN23 = "Asia/Shanghai"
CN24 = "Asia/Chongqing"
CN25 = "Asia/Shanghai"
CN26 = "Asia/Chongqing"
CN28 = "Asia/Shanghai"
CN29 = "Asia/Chongqing"
CN30 = "Asia/Chongqing"
CN31 = "Asia/Chongqing"
CN32 = "Asia/Chongqing"
CN33 = "Asia/Chongqing"
CO = "America/Bogota"
CR = "America/Costa_Rica"
CU = "America/Havana"
CV = "Atlantic/Cape_Verde"
CW = "America/Curacao"
CX = "Indian/Christmas"
CY = "Asia/Nicosia"
CZ = "Europe/Prague"
DE = "Europe/Berlin"
DJ = "Africa/Djibouti"
DK = "Europe/Copenhagen"
DM = "America/Dominica"
DO = "America/Santo_Domingo"
DZ = "Africa/Algiers"
EC01 = "Pacific/Galapagos"
EC02 = "America/Guayaquil"
EC03 = "America/Guayaquil"
EC04 = "America/Guayaquil"
EC05 = "America/Guayaquil"
EC06 = "America/Guayaquil"
EC07 = "America/Guayaquil"
EC08 = "America/Guayaquil"
EC09 = "America/Guayaquil"
EC10 = "America/Guayaquil"
EC11 = "America/Guayaquil"
EC12 = "America/Guayaquil"
EC13 = "America/Guayaquil"
EC14 = "America/Guayaquil"
EC15 = "America/Guayaquil"
EC17 = "America/Guayaquil"
EC18 = "America/Guayaquil"
EC19 = "America/Guayaquil"
EC20 = "America/Guayaquil"
EC22 = "America/Guayaquil"
EC24 = "America/Guayaquil"
EE = "Europe/Tallinn"
EG = "Africa/Cairo"
EH = "Africa/El_Aaiun"
ER = "Africa/Asmara"
ES07 = "Europe/Madrid"
ES27 = "Europe/Madrid"
ES29 = "Europe/Madrid"
ES31 = "Europe/Madrid"
ES32 = "Europe/Madrid"
ES34 = "Europe/Madrid"
ES39 = "Europe/Madrid"
ES51 = "Africa/Ceuta"
ES52 = "Europe/Madrid"
ES53 = "Atlantic/Canary"
ES54 = "Europe/Madrid"
ES55 = "Europe/Madrid"
ES56 = "Europe/Madrid"
ES57 = "Europe/Madrid"
ES58 = "Europe/Madrid"
ES59 = "Europe/Madrid"
ES60 = "Europe/Madrid"
ET = "Africa/Addis_Ababa"
FI = "Europe/Helsinki"
FJ = "Pacific/Fiji"
FK = "Atlantic/Stanley"
FM = "Pacific/Pohnpei"
FO = "Atlantic/Faroe"
FR = "Europe/Paris"
FX = "Europe/Paris"
GA = "Africa/Libreville"
GB = "Europe/London"
GD = "America/Grenada"
GE = "Asia/Tbilisi"
GF = "America/Cayenne"
GG = "Europe/Guernsey"
GH = "Africa/Accra"
GI = "Europe/Gibraltar"
GL01 = "America/Thule"
GL02 = "America/Godthab"
GL03 = "America/Godthab"
GM = "Africa/Banjul"
GN = "Africa/Conakry"
GP = "America/Guadeloupe"
GQ = "Africa/Malabo"
GR = "Europe/Athens"
GS = "Atlantic/South_Georgia"
GT = "America/Guatemala"
GU = "Pacific/Guam"
GW = "Africa/Bissau"
GY = "America/Guyana"
HK = "Asia/Hong_Kong"
HN = "America/Tegucigalpa"
HR = "Europe/Zagreb"
HT = "America/Port-au-Prince"
HU = "Europe/Budapest"
ID01 = "Asia/Pontianak"
ID02 = "Asia/Makassar"
ID03 = "Asia/Jakarta"
ID04 = "Asia/Jakarta"
ID05 = "Asia/Jakarta"
ID06 = "Asia/Jakarta"
ID07 = "Asia/Jakarta"
ID08 = "Asia/Jakarta"
ID09 = "Asia/Jayapura"
ID10 = "Asia/Jakarta"
ID11 = "Asia/Pontianak"
ID12 = "Asia/Makassar"
ID13 = "Asia/Makassar"
ID14 = "Asia/Makassar"
ID15 = "Asia/Jakarta"
ID16 = "Asia/Makassar"
ID17 = "Asia/Makassar"
ID18 = "Asia/Makassar"
ID19 = "Asia/Pontianak"
ID20 = "Asia/Makassar"
ID21 = "Asia/Makassar"
ID22 = "Asia/Makassar"
ID23 = "Asia/Makassar"
ID24 = "Asia/Jakarta"
ID25 = "Asia/Pontianak"
ID26 = "Asia/Pontianak"
ID28 = "Asia/Jayapura"
ID29 = "Asia/Makassar"
ID30 = "Asia/Jakarta"
ID31 = "Asia/Makassar"
ID32 = "Asia/Jakarta"
ID33 = "Asia/Jakarta"
ID34 = "Asia/Makassar"
ID35 = "Asia/Pontianak"
ID36 = "Asia/Jayapura"
ID37 = "Asia/Pontianak"
ID38 = "Asia/Makassar"
ID39 = "Asia/Jayapura"
ID40 = "Asia/Pontianak"
ID41 = "Asia/Makassar"
IE = "Europe/Dublin"
IL = "Asia/Jerusalem"
IM = "Europe/Isle_of_Man"
IN = "Asia/Kolkata"
IO = "Indian/Chagos"
IQ = "Asia/Baghdad"
IR = "Asia/Tehran"
IS = "Atlantic/Reykjavik"
IT = "Europe/Rome"
JE = "Europe/Jersey"
JM = "America/Jamaica"
JO = "Asia/Amman"
JP = "Asia/Tokyo"
KE = "Africa/Nairobi"
KG = "Asia/Bishkek"
KH = "Asia/Phnom_Penh"
KI = "Pacific/Tarawa"
KM = "Indian/Comoro"
KN = "America/St_Kitts"
KP = "Asia/Pyongyang"
KR = "Asia/Seoul"
KW = "Asia/Kuwait"
KY = "America/Cayman"
KZ01 = "Asia/Almaty"
KZ02 = "Asia/Almaty"
KZ03 = "Asia/Qyzylorda"
KZ04 = "Asia/Aqtobe"
KZ05 = "Asia/Qyzylorda"
KZ06 = "Asia/Aqtau"
KZ07 = "Asia/Oral"
KZ08 = "Asia/Qyzylorda"
KZ09 = "Asia/Aqtau"
KZ10 = "Asia/Qyzylorda"
KZ11 = "Asia/Almaty"
KZ12 = "Asia/Qyzylorda"
KZ13 = "Asia/Aqtobe"
KZ14 = "Asia/Qyzylorda"
KZ15 = "Asia/Almaty"
KZ16 = "Asia/Aqtobe"
KZ17 = "Asia/Almaty"
LA = "Asia/Vientiane"
LB = "Asia/Beirut"
LC = "America/St_Lucia"
LI = "Europe/Vaduz"
LK = "Asia/Colombo"
LR = "Africa/Monrovia"
LS = "Africa/Maseru"
LT = "Europe/Vilnius"
LU = "Europe/Luxembourg"
LV = "Europe/Riga"
LY = "Africa/Tripoli"
MA = "Africa/Casablanca"
MC = "Europe/Monaco"
MD = "Europe/Chisinau"
ME = "Europe/Podgorica"
MF = "America/Marigot"
MG = "Indian/Antananarivo"
MH = "Pacific/Kwajalein"
MK = "Europe/Skopje"
ML = "Africa/Bamako"
MM = "Asia/Rangoon"
MN06 = "Asia/Choibalsan"
MN11 = "Asia/Ulaanbaatar"
MN17 = "Asia/Choibalsan"
MN19 = "Asia/Hovd"
MN20 = "Asia/Ulaanbaatar"
MN21 = "Asia/Ulaanbaatar"
MN25 = "Asia/Ulaanbaatar"
MO = "Asia/Macau"
MP = "Pacific/Saipan"
MQ = "America/Martinique"
MR = "Africa/Nouakchott"
MS = "America/Montserrat"
MT = "Europe/Malta"
MU = "Indian/Mauritius"
MV = "Indian/Maldives"
MW = "Africa/Blantyre"
MX01 = "America/Mexico_City"
MX02 = "America/Tijuana"
MX03 = "America/Hermosillo"
MX04 = "America/Merida"
MX05 = "America/Mexico_City"
MX06 = "America/Chihuahua"
MX07 = "America/Monterrey"
MX08 = "America/Mexico_City"
MX09 = "America/Mexico_City"
MX10 = "America/Mazatlan"
MX11 = "America/Mexico_City"
MX12 = "America/Mexico_City"
MX13 = "America/Mexico_City"
MX14 = "America/Mazatlan"
MX15 = "America/Chihuahua"
MX16 = "America/Mexico_City"
MX17 = "America/Mexico_City"
MX18 = "America/Mazatlan"
MX19 = "America/Monterrey"
MX20 = "America/Mexico_City"
MX21 = "America/Mexico_City"
MX22 = "America/Mexico_City"
MX23 = "America/Cancun"
MX24 = "America/Mexico_City"
MX25 = "America/Mazatlan"
MX26 = "America/Hermosillo"
MX27 = "America/Merida"
MX28 = "America/Monterrey"
MX29 = "America/Mexico_City"
MX30 = "America/Mexico_City"
MX31 = "America/Merida"
MX32 = "America/Monterrey"
MY01 = "Asia/Kuala_Lumpur"
MY02 = "Asia/Kuala_Lumpur"
MY03 = "Asia/Kuala_Lumpur"
MY04 = "Asia/Kuala_Lumpur"
MY05 = "Asia/Kuala_Lumpur"
MY06 = "Asia/Kuala_Lumpur"
MY07 = "Asia/Kuala_Lumpur"
MY08 = "Asia/Kuala_Lumpur"
MY09 = "Asia/Kuala_Lumpur"
MY11 = "Asia/Kuching"
MY12 = "Asia/Kuala_Lumpur"
MY13 = "Asia/Kuala_Lumpur"
MY14 = "Asia/Kuala_Lumpur"
MY15 = "Asia/Kuching"
MY16 = "Asia/Kuching"
MZ = "Africa/Maputo"
NA = "Africa/Windhoek"
NC = "Pacific/Noumea"
NE = "Africa/Niamey"
NF = "Pacific/Norfolk"
NG = "Africa/Lagos"
NI = "America/Managua"
NL = "Europe/Amsterdam"
NO = "Europe/Oslo"
NP = "Asia/Kathmandu"
NR = "Pacific/Nauru"
NU = "Pacific/Niue"
NZ85 = "Pacific/Auckland"
NZE7 = "Pacific/Auckland"
NZE8 = "Pacific/Auckland"
NZE9 = "Pacific/Auckland"
NZF1 = "Pacific/Auckland"
NZF2 = "Pacific/Auckland"
NZF3 = "Pacific/Auckland"
NZF4 = "Pacific/Auckland"
NZF5 = "Pacific/Auckland"
NZF6 = "Pacific/Auckland"
NZF7 = "Pacific/Chatham"
NZF8 = "Pacific/Auckland"
NZF9 = "Pacific/Auckland"
NZG1 = "Pacific/Auckland"
NZG2 = "Pacific/Auckland"
NZG3 = "Pacific/Auckland"
OM = "Asia/Muscat"
PA = "America/Panama"
PE = "America/Lima"
PF = "Pacific/Marquesas"
PG = "Pacific/Port_Moresby"
PH = "Asia/Manila"
PK = "Asia/Karachi"
PL = "Europe/Warsaw"
PM = "America/Miquelon"
PN = "Pacific/Pitcairn"
PR = "America/Puerto_Rico"
PS = "Asia/Gaza"
PT02 = "Europe/Lisbon"
PT03 = "Europe/Lisbon"
PT04 = "Europe/Lisbon"
PT05 = "Europe/Lisbon"
PT06 = "Europe/Lisbon"
PT07 = "Europe/Lisbon"
PT08 = "Europe/Lisbon"
PT09 = "Europe/Lisbon"
PT10 = "Atlantic/Madeira"
PT11 = "Europe/Lisbon"
PT13 = "Europe/Lisbon"
PT14 = "Europe/Lisbon"
PT16 = "Europe/Lisbon"
PT17 = "Europe/Lisbon"
PT18 = "Europe/Lisbon"
PT19 = "Europe/Lisbon"
PT20 = "Europe/Lisbon"
PT21 = "Europe/Lisbon"
PT22 = "Europe/Lisbon"
PT23 = "Atlantic/Azores"
PW = "Pacific/Palau"
PY = "America/Asuncion"
QA = "Asia/Qatar"
RE = "Indian/Reunion"
RO = "Europe/Bucharest"
RS = "Europe/Belgrade"
RU01 = "Europe/Volgograd"
RU02 = "Asia/Irkutsk"
RU03 = "Asia/Novokuznetsk"
RU04 = "Asia/Novosibirsk"
RU05 = "Asia/Vladivostok"
RU06 = "Europe/Moscow"
RU07 = "Europe/Volgograd"
RU08 = "Europe/Samara"
RU09 = "Europe/Moscow"
RU10 = "Europe/Moscow"
RU11 = "Asia/Irkutsk"
RU12 = "Europe/Volgograd"
RU13 = "Asia/Yekaterinburg"
RU14 = "Asia/Irkutsk"
RU15 = "Asia/Anadyr"
RU16 = "Europe/Samara"
RU17 = "Europe/Volgograd"
RU18 = "Asia/Krasnoyarsk"
RU20 = "Asia/Irkutsk"
RU21 = "Europe/Moscow"
RU22 = "Europe/Volgograd"
RU23 = "Europe/Kaliningrad"
RU24 = "Europe/Volgograd"
RU25 = "Europe/Moscow"
RU26 = "Asia/Kamchatka"
RU27 = "Europe/Volgograd"
RU28 = "Europe/Moscow"
RU29 = "Asia/Novokuznetsk"
RU30 = "Asia/Vladivostok"
RU31 = "Asia/Krasnoyarsk"
RU32 = "Asia/Omsk"
RU33 = "Asia/Yekaterinburg"
RU34 = "Asia/Yekaterinburg"
RU35 = "Asia/Yekaterinburg"
RU36 = "Asia/Anadyr"
RU37 = "Europe/Moscow"
RU38 = "Europe/Volgograd"
RU39 = "Asia/Krasnoyarsk"
RU40 = "Asia/Yekaterinburg"
RU41 = "Europe/Moscow"
RU42 = "Europe/Moscow"
RU43 = "Europe/Moscow"
RU44 = "Asia/Magadan"
RU45 = "Europe/Samara"
RU46 = "Europe/Samara"
RU47 = "Europe/Moscow"
RU48 = "Europe/Moscow"
RU49 = "Europe/Moscow"
RU50 = "Asia/Yekaterinburg"
RU51 = "Europe/Moscow"
RU52 = "Europe/Moscow"
RU53 = "Asia/Novosibirsk"
RU54 = "Asia/Omsk"
RU55 = "Europe/Samara"
RU56 = "Europe/Moscow"
RU57 = "Europe/Samara"
RU58 = "Asia/Yekaterinburg"
RU59 = "Asia/Vladivostok"
RU60 = "Europe/Kaliningrad"
RU61 = "Europe/Volgograd"
RU62 = "Europe/Moscow"
RU63 = "Asia/Yakutsk"
RU64 = "Asia/Sakhalin"
RU65 = "Europe/Samara"
RU66 = "Europe/Moscow"
RU67 = "Europe/Samara"
RU68 = "Europe/Volgograd"
RU69 = "Europe/Moscow"
RU70 = "Europe/Volgograd"
RU71 = "Asia/Yekaterinburg"
RU72 = "Europe/Moscow"
RU73 = "Europe/Samara"
RU74 = "Asia/Krasnoyarsk"
RU75 = "Asia/Novosibirsk"
RU76 = "Europe/Moscow"
RU77 = "Europe/Moscow"
RU78 = "Asia/Yekaterinburg"
RU79 = "Asia/Irkutsk"
RU80 = "Asia/Yekaterinburg"
RU81 = "Europe/Samara"
RU82 = "Asia/Irkutsk"
RU83 = "Europe/Moscow"
RU84 = "Europe/Volgograd"
RU85 = "Europe/Moscow"
RU86 = "Europe/Moscow"
RU87 = "Asia/Novosibirsk"
RU88 = "Europe/Moscow"
RU89 = "Asia/Vladivostok"
RU90 = "Asia/Yekaterinburg"
RU91 = "Asia/Krasnoyarsk"
RU92 = "Asia/Anadyr"
RU93 = "Asia/Irkutsk"
RW = "Africa/Kigali"
SA = "Asia/Riyadh"
SB = "Pacific/Guadalcanal"
SC = "Indian/Mahe"
SD = "Africa/Khartoum"
SE = "Europe/Stockholm"
SG = "Asia/Singapore"
SH = "Atlantic/St_Helena"
SI = "Europe/Ljubljana"
SJ = "Arctic/Longyearbyen"
SK = "Europe/Bratislava"
SL = "Africa/Freetown"
SM = "Europe/San_Marino"
SN = "Africa/Dakar"
SO = "Africa/Mogadishu"
SR = "America/Paramaribo"
SS = "Africa/Juba"
ST = "Africa/Sao_Tome"
SV = "America/El_Salvador"
SX = "America/Curacao"
SY = "Asia/Damascus"
SZ = "Africa/Mbabane"
TC = "America/Grand_Turk"
TD = "Africa/Ndjamena"
TF = "Indian/Kerguelen"
TG = "Africa/Lome"
TH = "Asia/Bangkok"
TJ = "Asia/Dushanbe"
TK = "Pacific/Fakaofo"
TL = "Asia/Dili"
TM = "Asia/Ashgabat"
TN = "Africa/Tunis"
TO = "Pacific/Tongatapu"
TR = "Asia/Istanbul"
TT = "America/Port_of_Spain"
TV = "Pacific/Funafuti"
TW = "Asia/Taipei"
TZ = "Africa/Dar_es_Salaam"
UA01 = "Europe/Kiev"
UA02 = "Europe/Kiev"
UA03 = "Europe/Uzhgorod"
UA04 = "Europe/Zaporozhye"
UA05 = "Europe/Zaporozhye"
UA06 = "Europe/Uzhgorod"
UA07 = "Europe/Zaporozhye"
UA08 = "Europe/Simferopol"
UA09 = "Europe/Kiev"
UA10 = "Europe/Zaporozhye"
UA11 = "Europe/Simferopol"
UA12 = "Europe/Kiev"
UA13 = "Europe/Kiev"
UA14 = "Europe/Zaporozhye"
UA15 = "Europe/Uzhgorod"
UA16 = "Europe/Zaporozhye"
UA17 = "Europe/Simferopol"
UA18 = "Europe/Zaporozhye"
UA19 = "Europe/Kiev"
UA20 = "Europe/Simferopol"
UA21 = "Europe/Kiev"
UA22 = "Europe/Uzhgorod"
UA23 = "Europe/Kiev"
UA24 = "Europe/Uzhgorod"
UA25 = "Europe/Uzhgorod"
UA26 = "Europe/Zaporozhye"
UA27 = "Europe/Kiev"
UG = "Africa/Kampala"
UM = "Pacific/Wake"
USAK = "America/Anchorage"
USAL = "America/Chicago"
USAR = "America/Chicago"
USAZ = "America/Phoenix"
USCA = "America/Los_Angeles"
USCO = "America/Denver"
USCT = "America/New_York"
USDC = "America/New_York"
USDE = "America/New_York"
USFL = "America/New_York"
USGA = "America/New_York"
USHI = "Pacific/Honolulu"
USIA = "America/Chicago"
USID = "America/Denver"
USIL = "America/Chicago"
USIN = "America/Indiana/Indianapolis"
USKS = "America/Chicago"
USKY = "America/New_York"
USLA = "America/Chicago"
USMA = "America/New_York"
USMD = "America/New_York"
USME = "America/New_York"
USMI = "America/New_York"
USMN = "America/Chicago"
USMO = "America/Chicago"
USMS = "America/Chicago"
USMT = "America/Denver"
USNC = "America/New_York"
USND = "America/Chicago"
USNE = "America/Chicago"
USNH = "America/New_York"
USNJ = "America/New_York"
USNM = "America/Denver"
USNV = "America/Los_Angeles"
USNY = "America/New_York"
USOH = "America/New_York"
USOK = "America/Chicago"
USOR = "America/Los_Angeles"
USPA = "America/New_York"
USRI = "America/New_York"
USSC = "America/New_York"
USSD = "America/Chicago"
USTN = "America/Chicago"
USTX = "America/Chicago"
USUT = "America/Denver"
USVA = "America/New_York"
USVT = "America/New_York"
USWA = "America/Los_Angeles"
USWI = "America/Chicago"
USWV = "America/New_York"
USWY = "America/Denver"
UY = "America/Montevideo"
UZ01 = "Asia/Tashkent"
UZ02 = "Asia/Samarkand"
UZ03 = "Asia/Tashkent"
UZ05 = "Asia/Samarkand"
UZ06 = "Asia/Tashkent"
UZ07 = "Asia/Samarkand"
UZ08 = "Asia/Samarkand"
UZ09 = "Asia/Samarkand"
UZ10 = "Asia/Samarkand"
UZ12 = "Asia/Samarkand"
UZ13 = "Asia/Tashkent"
UZ14 = "Asia/Tashkent"
VA = "Europe/Vatican"
VC = "America/St_Vincent"
VE = "America/Caracas"
VG = "America/Tortola"
VI = "America/St_Thomas"
VN = "Asia/Phnom_Penh"
VU = "Pacific/Efate"
WF = "Pacific/Wallis"
WS = "Pacific/Pago_Pago"
YE = "Asia/Aden"
YT = "Indian/Mayotte"
YU = "Europe/Belgrade"
ZA = "Africa/Johannesburg"
ZM = "Africa/Lusaka"
ZW = "Africa/Harare"
