// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/mozilla-services/heka/pipeline (interfaces: PluginHelper)

package pipeline

import (
	gomock "code.google.com/p/gomock/gomock"
)

// Mock of PluginHelper interface
type MockPluginHelper struct {
	ctrl     *gomock.Controller
	recorder *_MockPluginHelperRecorder
}

// Recorder for MockPluginHelper (not exported)
type _MockPluginHelperRecorder struct {
	mock *MockPluginHelper
}

func NewMockPluginHelper(ctrl *gomock.Controller) *MockPluginHelper {
	mock := &MockPluginHelper{ctrl: ctrl}
	mock.recorder = &_MockPluginHelperRecorder{mock}
	return mock
}

func (_m *MockPluginHelper) EXPECT() *_MockPluginHelperRecorder {
	return _m.recorder
}

func (_m *MockPluginHelper) AddFilterRunner(_param0 FilterRunner) error {
	ret := _m.ctrl.Call(_m, "AddFilterRunner", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockPluginHelperRecorder) AddFilterRunner(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AddFilterRunner", arg0)
}

func (_m *MockPluginHelper) Decoder(_param0 string) (DecoderRunner, bool) {
	ret := _m.ctrl.Call(_m, "Decoder", _param0)
	ret0, _ := ret[0].(DecoderRunner)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

func (_mr *_MockPluginHelperRecorder) Decoder(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Decoder", arg0)
}

func (_m *MockPluginHelper) Decoders() map[string]DecoderRunner {
	ret := _m.ctrl.Call(_m, "Decoders")
	ret0, _ := ret[0].(map[string]DecoderRunner)
	return ret0
}

func (_mr *_MockPluginHelperRecorder) Decoders() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Decoders")
}

func (_m *MockPluginHelper) DecodersByEncoding() []DecoderRunner {
	ret := _m.ctrl.Call(_m, "DecodersByEncoding")
	ret0, _ := ret[0].([]DecoderRunner)
	return ret0
}

func (_mr *_MockPluginHelperRecorder) DecodersByEncoding() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DecodersByEncoding")
}

func (_m *MockPluginHelper) FindFilterRunner(_param0 string) (FilterRunner, bool) {
	ret := _m.ctrl.Call(_m, "FindFilterRunner", _param0)
	ret0, _ := ret[0].(FilterRunner)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

func (_mr *_MockPluginHelperRecorder) FindFilterRunner(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "FindFilterRunner", arg0)
}

func (_m *MockPluginHelper) Output(_param0 string) (OutputRunner, bool) {
	ret := _m.ctrl.Call(_m, "Output", _param0)
	ret0, _ := ret[0].(OutputRunner)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

func (_mr *_MockPluginHelperRecorder) Output(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Output", arg0)
}

func (_m *MockPluginHelper) PackSupply() chan *PipelinePack {
	ret := _m.ctrl.Call(_m, "PackSupply")
	ret0, _ := ret[0].(chan *PipelinePack)
	return ret0
}

func (_mr *_MockPluginHelperRecorder) PackSupply() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PackSupply")
}

func (_m *MockPluginHelper) RemoveFilterRunner(_param0 string) {
	_m.ctrl.Call(_m, "RemoveFilterRunner", _param0)
}

func (_mr *_MockPluginHelperRecorder) RemoveFilterRunner(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "RemoveFilterRunner", arg0)
}

func (_m *MockPluginHelper) Router() *MessageRouter {
	ret := _m.ctrl.Call(_m, "Router")
	ret0, _ := ret[0].(*MessageRouter)
	return ret0
}

func (_mr *_MockPluginHelperRecorder) Router() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Router")
}
