// Automatically generated by MockGen. DO NOT EDIT!
// Source: heka/pipeline (interfaces: Input)

package pipeline

import (
	gomock "code.google.com/p/gomock/gomock"
	time "time"
)

// Mock of Input interface
type MockInput struct {
	ctrl     *gomock.Controller
	recorder *_MockInputRecorder
}

// Recorder for MockInput (not exported)
type _MockInputRecorder struct {
	mock *MockInput
}

func NewMockInput(ctrl *gomock.Controller) *MockInput {
	mock := &MockInput{ctrl: ctrl}
	mock.recorder = &_MockInputRecorder{mock}
	return mock
}

func (_m *MockInput) EXPECT() *_MockInputRecorder {
	return _m.recorder
}

func (_m *MockInput) Init(_param0 interface{}) error {
	ret := _m.ctrl.Call(_m, "Init", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockInputRecorder) Init(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Init", arg0)
}

func (_m *MockInput) Read(_param0 *PipelinePack, _param1 *time.Duration) error {
	ret := _m.ctrl.Call(_m, "Read", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockInputRecorder) Read(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Read", arg0, arg1)
}
