// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/mozilla-services/heka/pipeline (interfaces: DecoderSet)

package pipeline

import (
	gomock "code.google.com/p/gomock/gomock"
	message "github.com/mozilla-services/heka/message"
)

// Mock of DecoderSet interface
type MockDecoderSet struct {
	ctrl     *gomock.Controller
	recorder *_MockDecoderSetRecorder
}

// Recorder for MockDecoderSet (not exported)
type _MockDecoderSetRecorder struct {
	mock *MockDecoderSet
}

func NewMockDecoderSet(ctrl *gomock.Controller) *MockDecoderSet {
	mock := &MockDecoderSet{ctrl: ctrl}
	mock.recorder = &_MockDecoderSetRecorder{mock}
	return mock
}

func (_m *MockDecoderSet) EXPECT() *_MockDecoderSetRecorder {
	return _m.recorder
}

func (_m *MockDecoderSet) AllByName() map[string]DecoderRunner {
	ret := _m.ctrl.Call(_m, "AllByName")
	ret0, _ := ret[0].(map[string]DecoderRunner)
	return ret0
}

func (_mr *_MockDecoderSetRecorder) AllByName() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "AllByName")
}

func (_m *MockDecoderSet) ByEncoding(_param0 message.Header_MessageEncoding) (DecoderRunner, bool) {
	ret := _m.ctrl.Call(_m, "ByEncoding", _param0)
	ret0, _ := ret[0].(DecoderRunner)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

func (_mr *_MockDecoderSetRecorder) ByEncoding(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ByEncoding", arg0)
}

func (_m *MockDecoderSet) ByName(_param0 string) (DecoderRunner, bool) {
	ret := _m.ctrl.Call(_m, "ByName", _param0)
	ret0, _ := ret[0].(DecoderRunner)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

func (_mr *_MockDecoderSetRecorder) ByName(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ByName", arg0)
}
