# heka image
# installs heka from a deb package
FROM debian:jessie
MAINTAINER Chance Zibolski <chance.zibolski@gmail.com> (@chance)

COPY heka.deb /tmp/heka.deb
RUN dpkg -i /tmp/heka.deb && rm /tmp/heka.deb

EXPOSE 4352
ENTRYPOINT ["hekad"]
