[UdpInput]
address = "127.0.0.1:29329"
parser_type = "message.proto"
decoder = "ProtobufDecoder"

[LogOutput]

[StatFilter]

[sample]
type = "StatFilter"
message_matcher = "Type == 'counter' || Type == 'gauge'"
