[UdpInput]
address = "127.0.0.1:5565"

[UdpInput.retries]
max_delay = "30s"
delay = "250ms"
max_retries = 5

[CounterFilter]
message_matcher = "Type != 'heka.counter-output'"
message_signer = "some_signer"
ticker_interval = 10

