[udp_stats]
type = "UdpInput"
address = "127.0.0.1:29330"
parser_type = "message.proto"
decoder = "ProtobufDecoder"

[JsonDecoder]
type ="JsonDecoder"
encoding_name = "JSON"

[WhatOutput]
type ="WhatOutput"
