[UdpInput1]
address = "127.0.0.1:29329"
parser_type = "message.proto"
decoder = "ProtobufDecoder"

[JsonDecoder1]
type ="JsonDecoder"
encoding_name = "JSON"

[ProtobufDecoder1]
type = "ProtobufDecoder"
encoding_name = "PROTOCOL_BUFFER"

[LogOutput1]
type = "LogOutput"
