[UdpInput1]
address = "127.0.0.1:29329"
parser_type = "message.proto"
decoder = "ProtobufDecoder"

[JsonDecoder1]
type ="JsonDecoder"

[ProtobufDecoder1]
type = "ProtobufDecoder"

[LogOutput1]
type = "LogOutput"
