// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Header_MessageEncoding int32

const (
	Header_PROTOCOL_BUFFER Header_MessageEncoding = 0
	Header_JSON            Header_MessageEncoding = 1
)

var Header_MessageEncoding_name = map[int32]string{
	0: "PROTOCOL_BUFFER",
	1: "JSON",
}
var Header_MessageEncoding_value = map[string]int32{
	"PROTOCOL_BUFFER": 0,
	"JSON":            1,
}

func (x Header_MessageEncoding) Enum() *Header_MessageEncoding {
	p := new(Header_MessageEncoding)
	*p = x
	return p
}
func (x Header_MessageEncoding) String() string {
	return proto.EnumName(Header_MessageEncoding_name, int32(x))
}
func (x Header_MessageEncoding) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Header_MessageEncoding) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Header_MessageEncoding_value, data, "Header_MessageEncoding")
	if err != nil {
		return err
	}
	*x = Header_MessageEncoding(value)
	return nil
}

type Field_ValueType int32

const (
	Field_STRING  Field_ValueType = 0
	Field_BYTES   Field_ValueType = 1
	Field_INTEGER Field_ValueType = 2
	Field_DOUBLE  Field_ValueType = 3
	Field_BOOL    Field_ValueType = 4
)

var Field_ValueType_name = map[int32]string{
	0: "STRING",
	1: "BYTES",
	2: "INTEGER",
	3: "DOUBLE",
	4: "BOOL",
}
var Field_ValueType_value = map[string]int32{
	"STRING":  0,
	"BYTES":   1,
	"INTEGER": 2,
	"DOUBLE":  3,
	"BOOL":    4,
}

func (x Field_ValueType) Enum() *Field_ValueType {
	p := new(Field_ValueType)
	*p = x
	return p
}
func (x Field_ValueType) String() string {
	return proto.EnumName(Field_ValueType_name, int32(x))
}
func (x Field_ValueType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Field_ValueType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Field_ValueType_value, data, "Field_ValueType")
	if err != nil {
		return err
	}
	*x = Field_ValueType(value)
	return nil
}

type Field_ValueFormat int32

const (
	Field_RAW             Field_ValueFormat = 0
	Field_DATE_RFC3339    Field_ValueFormat = 1
	Field_UTC_SECONDS     Field_ValueFormat = 2
	Field_UTC_NANOSECONDS Field_ValueFormat = 3
)

var Field_ValueFormat_name = map[int32]string{
	0: "RAW",
	1: "DATE_RFC3339",
	2: "UTC_SECONDS",
	3: "UTC_NANOSECONDS",
}
var Field_ValueFormat_value = map[string]int32{
	"RAW":             0,
	"DATE_RFC3339":    1,
	"UTC_SECONDS":     2,
	"UTC_NANOSECONDS": 3,
}

func (x Field_ValueFormat) Enum() *Field_ValueFormat {
	p := new(Field_ValueFormat)
	*p = x
	return p
}
func (x Field_ValueFormat) String() string {
	return proto.EnumName(Field_ValueFormat_name, int32(x))
}
func (x Field_ValueFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Field_ValueFormat) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Field_ValueFormat_value, data, "Field_ValueFormat")
	if err != nil {
		return err
	}
	*x = Field_ValueFormat(value)
	return nil
}

type Header struct {
	MessageLength    *uint32                 `protobuf:"varint,1,req,name=message_length" json:"message_length,omitempty"`
	MessageEncoding  *Header_MessageEncoding `protobuf:"varint,2,opt,name=message_encoding,enum=message.Header_MessageEncoding,def=0" json:"message_encoding,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (this *Header) Reset()         { *this = Header{} }
func (this *Header) String() string { return proto.CompactTextString(this) }
func (*Header) ProtoMessage()       {}

const Default_Header_MessageEncoding Header_MessageEncoding = Header_PROTOCOL_BUFFER

func (this *Header) GetMessageLength() uint32 {
	if this != nil && this.MessageLength != nil {
		return *this.MessageLength
	}
	return 0
}

func (this *Header) GetMessageEncoding() Header_MessageEncoding {
	if this != nil && this.MessageEncoding != nil {
		return *this.MessageEncoding
	}
	return Default_Header_MessageEncoding
}

type Field struct {
	Name             *string            `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	ValueType        *Field_ValueType   `protobuf:"varint,2,opt,name=value_type,enum=message.Field_ValueType,def=0" json:"value_type,omitempty"`
	ValueFormat      *Field_ValueFormat `protobuf:"varint,3,opt,name=value_format,enum=message.Field_ValueFormat,def=0" json:"value_format,omitempty"`
	ValueString      []string           `protobuf:"bytes,4,rep,name=value_string" json:"value_string,omitempty"`
	ValueBytes       [][]byte           `protobuf:"bytes,5,rep,name=value_bytes" json:"value_bytes,omitempty"`
	ValueInteger     []int64            `protobuf:"varint,6,rep,packed,name=value_integer" json:"value_integer,omitempty"`
	ValueDouble      []float64          `protobuf:"fixed64,7,rep,packed,name=value_double" json:"value_double,omitempty"`
	ValueBool        []bool             `protobuf:"varint,8,rep,packed,name=value_bool" json:"value_bool,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (this *Field) Reset()         { *this = Field{} }
func (this *Field) String() string { return proto.CompactTextString(this) }
func (*Field) ProtoMessage()       {}

const Default_Field_ValueType Field_ValueType = Field_STRING
const Default_Field_ValueFormat Field_ValueFormat = Field_RAW

func (this *Field) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Field) GetValueType() Field_ValueType {
	if this != nil && this.ValueType != nil {
		return *this.ValueType
	}
	return Default_Field_ValueType
}

func (this *Field) GetValueFormat() Field_ValueFormat {
	if this != nil && this.ValueFormat != nil {
		return *this.ValueFormat
	}
	return Default_Field_ValueFormat
}

type Message struct {
	Uuid             []byte   `protobuf:"bytes,1,req,name=uuid" json:"uuid,omitempty"`
	Timestamp        *int64   `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	Type             *string  `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Logger           *string  `protobuf:"bytes,4,opt,name=logger" json:"logger,omitempty"`
	Severity         *int32   `protobuf:"varint,5,opt,name=severity" json:"severity,omitempty"`
	Payload          *string  `protobuf:"bytes,6,opt,name=payload" json:"payload,omitempty"`
	EnvVersion       *string  `protobuf:"bytes,7,opt,name=env_version" json:"env_version,omitempty"`
	Pid              *int32   `protobuf:"varint,8,opt,name=pid" json:"pid,omitempty"`
	Hostname         *string  `protobuf:"bytes,9,opt,name=hostname" json:"hostname,omitempty"`
	Fields           []*Field `protobuf:"bytes,10,rep,name=fields" json:"fields,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *Message) Reset()         { *this = Message{} }
func (this *Message) String() string { return proto.CompactTextString(this) }
func (*Message) ProtoMessage()       {}

func (this *Message) GetUuid() []byte {
	if this != nil {
		return this.Uuid
	}
	return nil
}

func (this *Message) GetTimestamp() int64 {
	if this != nil && this.Timestamp != nil {
		return *this.Timestamp
	}
	return 0
}

func (this *Message) GetType() string {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return ""
}

func (this *Message) GetLogger() string {
	if this != nil && this.Logger != nil {
		return *this.Logger
	}
	return ""
}

func (this *Message) GetSeverity() int32 {
	if this != nil && this.Severity != nil {
		return *this.Severity
	}
	return 0
}

func (this *Message) GetPayload() string {
	if this != nil && this.Payload != nil {
		return *this.Payload
	}
	return ""
}

func (this *Message) GetEnvVersion() string {
	if this != nil && this.EnvVersion != nil {
		return *this.EnvVersion
	}
	return ""
}

func (this *Message) GetPid() int32 {
	if this != nil && this.Pid != nil {
		return *this.Pid
	}
	return 0
}

func (this *Message) GetHostname() string {
	if this != nil && this.Hostname != nil {
		return *this.Hostname
	}
	return ""
}

func init() {
	proto.RegisterEnum("message.Header_MessageEncoding", Header_MessageEncoding_name, Header_MessageEncoding_value)
	proto.RegisterEnum("message.Field_ValueType", Field_ValueType_name, Field_ValueType_value)
	proto.RegisterEnum("message.Field_ValueFormat", Field_ValueFormat_name, Field_ValueFormat_value)
}
