// Code generated by protoc-gen-go.
// source: message.proto
// DO NOT EDIT!

package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Header_MessageEncoding int32

const (
	Header_PROTOCOL_BUFFER Header_MessageEncoding = 0
	Header_JSON            Header_MessageEncoding = 1
)

var Header_MessageEncoding_name = map[int32]string{
	0: "PROTOCOL_BUFFER",
	1: "JSON",
}
var Header_MessageEncoding_value = map[string]int32{
	"PROTOCOL_BUFFER": 0,
	"JSON":            1,
}

func (x Header_MessageEncoding) Enum() *Header_MessageEncoding {
	p := new(Header_MessageEncoding)
	*p = x
	return p
}
func (x Header_MessageEncoding) String() string {
	return proto.EnumName(Header_MessageEncoding_name, int32(x))
}
func (x Header_MessageEncoding) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Header_MessageEncoding) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Header_MessageEncoding_value, data, "Header_MessageEncoding")
	if err != nil {
		return err
	}
	*x = Header_MessageEncoding(value)
	return nil
}

type Header_HmacHashFunction int32

const (
	Header_MD5  Header_HmacHashFunction = 0
	Header_SHA1 Header_HmacHashFunction = 1
)

var Header_HmacHashFunction_name = map[int32]string{
	0: "MD5",
	1: "SHA1",
}
var Header_HmacHashFunction_value = map[string]int32{
	"MD5":  0,
	"SHA1": 1,
}

func (x Header_HmacHashFunction) Enum() *Header_HmacHashFunction {
	p := new(Header_HmacHashFunction)
	*p = x
	return p
}
func (x Header_HmacHashFunction) String() string {
	return proto.EnumName(Header_HmacHashFunction_name, int32(x))
}
func (x Header_HmacHashFunction) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Header_HmacHashFunction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Header_HmacHashFunction_value, data, "Header_HmacHashFunction")
	if err != nil {
		return err
	}
	*x = Header_HmacHashFunction(value)
	return nil
}

type Field_ValueType int32

const (
	Field_STRING  Field_ValueType = 0
	Field_BYTES   Field_ValueType = 1
	Field_INTEGER Field_ValueType = 2
	Field_DOUBLE  Field_ValueType = 3
	Field_BOOL    Field_ValueType = 4
)

var Field_ValueType_name = map[int32]string{
	0: "STRING",
	1: "BYTES",
	2: "INTEGER",
	3: "DOUBLE",
	4: "BOOL",
}
var Field_ValueType_value = map[string]int32{
	"STRING":  0,
	"BYTES":   1,
	"INTEGER": 2,
	"DOUBLE":  3,
	"BOOL":    4,
}

func (x Field_ValueType) Enum() *Field_ValueType {
	p := new(Field_ValueType)
	*p = x
	return p
}
func (x Field_ValueType) String() string {
	return proto.EnumName(Field_ValueType_name, int32(x))
}
func (x Field_ValueType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Field_ValueType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Field_ValueType_value, data, "Field_ValueType")
	if err != nil {
		return err
	}
	*x = Field_ValueType(value)
	return nil
}

type Header struct {
	MessageLength    *uint32                  `protobuf:"varint,1,req,name=message_length" json:"message_length,omitempty"`
	MessageEncoding  *Header_MessageEncoding  `protobuf:"varint,2,opt,name=message_encoding,enum=message.Header_MessageEncoding,def=0" json:"message_encoding,omitempty"`
	HmacHashFunction *Header_HmacHashFunction `protobuf:"varint,3,opt,name=hmac_hash_function,enum=message.Header_HmacHashFunction,def=0" json:"hmac_hash_function,omitempty"`
	HmacSigner       *string                  `protobuf:"bytes,4,opt,name=hmac_signer" json:"hmac_signer,omitempty"`
	HmacKeyVersion   *uint32                  `protobuf:"varint,5,opt,name=hmac_key_version" json:"hmac_key_version,omitempty"`
	Hmac             []byte                   `protobuf:"bytes,6,opt,name=hmac" json:"hmac,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (this *Header) Reset()         { *this = Header{} }
func (this *Header) String() string { return proto.CompactTextString(this) }
func (*Header) ProtoMessage()       {}

const Default_Header_MessageEncoding Header_MessageEncoding = Header_PROTOCOL_BUFFER
const Default_Header_HmacHashFunction Header_HmacHashFunction = Header_MD5

func (this *Header) GetMessageLength() uint32 {
	if this != nil && this.MessageLength != nil {
		return *this.MessageLength
	}
	return 0
}

func (this *Header) GetMessageEncoding() Header_MessageEncoding {
	if this != nil && this.MessageEncoding != nil {
		return *this.MessageEncoding
	}
	return Default_Header_MessageEncoding
}

func (this *Header) GetHmacHashFunction() Header_HmacHashFunction {
	if this != nil && this.HmacHashFunction != nil {
		return *this.HmacHashFunction
	}
	return Default_Header_HmacHashFunction
}

func (this *Header) GetHmacSigner() string {
	if this != nil && this.HmacSigner != nil {
		return *this.HmacSigner
	}
	return ""
}

func (this *Header) GetHmacKeyVersion() uint32 {
	if this != nil && this.HmacKeyVersion != nil {
		return *this.HmacKeyVersion
	}
	return 0
}

func (this *Header) GetHmac() []byte {
	if this != nil {
		return this.Hmac
	}
	return nil
}

type Field struct {
	Name             *string          `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	ValueType        *Field_ValueType `protobuf:"varint,2,opt,name=value_type,enum=message.Field_ValueType,def=0" json:"value_type,omitempty"`
	Representation   *string          `protobuf:"bytes,3,opt,name=representation" json:"representation,omitempty"`
	ValueString      []string         `protobuf:"bytes,4,rep,name=value_string" json:"value_string,omitempty"`
	ValueBytes       [][]byte         `protobuf:"bytes,5,rep,name=value_bytes" json:"value_bytes,omitempty"`
	ValueInteger     []int64          `protobuf:"varint,6,rep,packed,name=value_integer" json:"value_integer,omitempty"`
	ValueDouble      []float64        `protobuf:"fixed64,7,rep,packed,name=value_double" json:"value_double,omitempty"`
	ValueBool        []bool           `protobuf:"varint,8,rep,packed,name=value_bool" json:"value_bool,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (this *Field) Reset()         { *this = Field{} }
func (this *Field) String() string { return proto.CompactTextString(this) }
func (*Field) ProtoMessage()       {}

const Default_Field_ValueType Field_ValueType = Field_STRING

func (this *Field) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Field) GetValueType() Field_ValueType {
	if this != nil && this.ValueType != nil {
		return *this.ValueType
	}
	return Default_Field_ValueType
}

func (this *Field) GetRepresentation() string {
	if this != nil && this.Representation != nil {
		return *this.Representation
	}
	return ""
}

type Message struct {
	Uuid             []byte   `protobuf:"bytes,1,req,name=uuid" json:"uuid,omitempty"`
	Timestamp        *int64   `protobuf:"varint,2,req,name=timestamp" json:"timestamp,omitempty"`
	Type             *string  `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Logger           *string  `protobuf:"bytes,4,opt,name=logger" json:"logger,omitempty"`
	Severity         *int32   `protobuf:"varint,5,opt,name=severity" json:"severity,omitempty"`
	Payload          *string  `protobuf:"bytes,6,opt,name=payload" json:"payload,omitempty"`
	EnvVersion       *string  `protobuf:"bytes,7,opt,name=env_version" json:"env_version,omitempty"`
	Pid              *int32   `protobuf:"varint,8,opt,name=pid" json:"pid,omitempty"`
	Hostname         *string  `protobuf:"bytes,9,opt,name=hostname" json:"hostname,omitempty"`
	Fields           []*Field `protobuf:"bytes,10,rep,name=fields" json:"fields,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *Message) Reset()         { *this = Message{} }
func (this *Message) String() string { return proto.CompactTextString(this) }
func (*Message) ProtoMessage()       {}

func (this *Message) GetUuid() []byte {
	if this != nil {
		return this.Uuid
	}
	return nil
}

func (this *Message) GetTimestamp() int64 {
	if this != nil && this.Timestamp != nil {
		return *this.Timestamp
	}
	return 0
}

func (this *Message) GetType() string {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return ""
}

func (this *Message) GetLogger() string {
	if this != nil && this.Logger != nil {
		return *this.Logger
	}
	return ""
}

func (this *Message) GetSeverity() int32 {
	if this != nil && this.Severity != nil {
		return *this.Severity
	}
	return 0
}

func (this *Message) GetPayload() string {
	if this != nil && this.Payload != nil {
		return *this.Payload
	}
	return ""
}

func (this *Message) GetEnvVersion() string {
	if this != nil && this.EnvVersion != nil {
		return *this.EnvVersion
	}
	return ""
}

func (this *Message) GetPid() int32 {
	if this != nil && this.Pid != nil {
		return *this.Pid
	}
	return 0
}

func (this *Message) GetHostname() string {
	if this != nil && this.Hostname != nil {
		return *this.Hostname
	}
	return ""
}

func init() {
	proto.RegisterEnum("message.Header_MessageEncoding", Header_MessageEncoding_name, Header_MessageEncoding_value)
	proto.RegisterEnum("message.Header_HmacHashFunction", Header_HmacHashFunction_name, Header_HmacHashFunction_value)
	proto.RegisterEnum("message.Field_ValueType", Field_ValueType_name, Field_ValueType_value)
}
